name: Deploy to NPM
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.name "KicKerBNU"
      - run: git config --global user.email "evertonbuzzi@gmail.com"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}
          github-token: ${{ secrets.GITHUB_TOKEN }}
